tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: ENC[AES256_GCM,data:xWoHBzCbcVME5PBCcpxZAOalclUvtOpYxLU8d5yyCeaUEJPDxWUCwwpFEnr7NUIsyn0uvFKb/ZpSpQ0m,iv:GEDqUn+wi3aOQrYoUgPG0nguyfrOefZhfGgS72lAStU=,tag:L2l8vBPw+KnYhlTj5XnG7Q==,type:str]
                username: ENC[AES256_GCM,data:P4Bn417AORAgo9GYHLdli9FHKha3Q3It96KmxlgGtXU=,iv:XAM21bFYxiWwBy7/FVAzP8mQy6Zm3VYuFL3ppnsP4NM=,tag:Mf4oRBia3PD2d9efsJXn0w==,type:str]
                password: ENC[AES256_GCM,data:+Y7g+IDwFvg8uRlcayI0iiw+WvH5kO2m/DxBPULzmw0vzr0HCktIHyyWokkJynwHJRDnmw==,iv:7e+PDwP5tBp1wEYOeqycwb//Ltmtjg6zGwdFHlxkKag=,tag:ey1vHe6jLAgG0eBXxs3fbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s3sgzav20qr07s77ewghvycs7wh5sn8jp03anj3t3f36tprm3ctswe2mwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQT0hWbUVGTGxiQmw0QnVj
            UEVMYUowS1orOUkvek8wdmJmUEF4Smx1UDFzCkZEQlVtcWJkczRseEZpd3pVNTE5
            U3pxZWdxOXhxVVhzRGRRTUdsMGNFMWcKLS0tIFZkdkNBc09MZU4rUzd1MktxZlhX
            akVhMzZnRyt2MHdyT3ZPK0ZZUEo4TDQK/VkH1u+k3mcB96xPTxstKzY5xFplZqtO
            6s4gSB6B42wkaK8ih7MqoXKkCBua91oo62fOQWCnnuoSFpPKiYQIfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-12T13:48:19Z"
    mac: ENC[AES256_GCM,data:YZHjJh5u4Jdpmc4fmqo35LHk5AIpapBbc68RgBvMguEGYgjDAcO8cJW35jik7gDEGCAcOY0sjdcWbrnLtHD5FlRp9lU9gD6HvNJ87GsqqfFkBH68E5HO2F6xMXuMku+zEEAukGG+HdZCP33gAqzjflXR0N+ZHiDqsvDcneye0cc=,iv:hVIXDngSxWdJCaL60GcEQjkpb43ldW9LEnm+sLWM63w=,tag:Zmk19svljIPPahvCuS/qsA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
